server:
  port: 8090

spring:
  security:
    user:
      name: user
      password: user
  jpa:
    open-in-view: false
    database: postgresql
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    url: jdbc:postgresql://localhost:5432/PostFlow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver