server:
  port: 8090

spring:
  security:
    user:
      name: user
      password: user
  jpa:
      database: postgresql
      show-sql: false
      generate-ddl: true
      hibernate:
          ddl-auto: update
      properties:
          hibernate:
              hbm2dll:
                  create_namespaces: true
              dialect: org.hibernate.dialect.PostgreSQLDialect
              jdbc:
                  lob:
                      non_contextual_creation: true

  datasource:
    url: jdbc:postgresql://localhost:5432/post_flow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    logging:
      level:
        root: DEBUG
      console:
        enabled: true